
import numpy as np
from scipy.stats import norm, gaussian_kde
import plotly.graph_objects as go

class ABTest():

	def __init__(self, a_samples, b_samples):
		self._a_samples = a_samples
		self._b_samples = b_samples

	# Given a vector of m data points, generates n permutations organized into an (n,m) matrix
	def _permute(self, data, m):
		# 1. Sample size
		n = np.size(data)

		# 2. Constructs a random matrix of shape (n,m)
		rand = np.random.randn(n,m)

		# 3. Orders each column of the matrix and returns a matrix
		#    of ordering indices
		indices = np.argsort(rand, axis = 0)

		# 4. Returns the sample over those indices
		return np.array(data)[indices]

	# Generates the delta distribution under the null hypothesis
	def generate_delta_distribution(self, N=1000):

		# 0. Renaming for interal use of this method, just for simplicity
		a_metrics = self._a_samples
		b_metrics = self._b_samples

		# 1. Puts all data together effectively forgetting the labels
		#    under the null hypothesis
		metrics = np.concatenate([a_metrics, b_metrics])

		# 2. Number of samples
		A = len(a_metrics)

		# 3. Resamples N times
		permutations = self._permute(metrics, N)

		# 3.1 The A permutations, shape (A,N)
		a_resamples = permutations[:A,:]

		# 3.2 The B permutations, shape (B,N) where B = len(metrics) - A
		b_resamples = permutations[A:,:]

		# 4. This is the distribution of \Delta = X_B - X_A
		#    under the null hypothesis

		delta_distribution = b_resamples.mean(axis = 0) - a_resamples.mean(axis = 0)

		return delta_distribution

	# Computes the p-value given the metrics for the A group and B group and a number N of resamples
	def compute_p_value(self, alternative = "two-sided", N = 1000):
		# 0. Renaming for interal use of this method, just for simplicity
		a_metrics = self._a_samples
		b_metrics = self._b_samples

		# 1. Generates delta distribution
		delta_distribution = self.generate_delta_distribution(N)

		# 2. This is the observed delta
		delta_obs = b_metrics.mean() - a_metrics.mean()

		# 3. The p-value depending on type of test. First we define
		#    the number of trues: the number of instances where we
		#    pick a delta more exreme than the true observed one

		if alternative == "greater":
			count = np.sum(delta_distribution >= delta_obs)
		elif alternative == "less":
			count = np.sum(delta_distribution <= delta_obs)
		elif alternative == "two-sided":
			count = np.sum(np.abs(delta_distribution) >= abs(delta_obs))
		else:
			raise ValueError("Alternative must be 'greater', 'less', or 'two-sided'")

		# 7. Returns the p-value with Monte Carlo correction
		return (count+1)/(N+1)

	# Computes the observed delta
	def compute_delta_obs(self):
		return self._b_samples.mean() - self._a_samples.mean()

	# Plots the delta distribution generated by permutatons. Can include
	# the prediction by the central limit theorem to compare.
	def plot_delta_distribution(self, N = 1000, include_clt = False, alternative = "two-sided"):

		# 0. Defines the delta distribution and observed delta
		delta_distribution = self.generate_delta_distribution(N)
		delta_obs = self.compute_delta_obs()

		# 1. Computes the KDE from the distribution manually
		kde = gaussian_kde(delta_distribution)
		x_range = np.linspace(min(delta_distribution), max(delta_distribution), 1000)
		kde_y = kde(x_range)

		# 2. Starts building the Plotly figure
		fig = go.Figure()

		# 2.1 Adds the Histogram (permutation test)
		fig.add_trace(go.Histogram(
			x=delta_distribution,
			histnorm='probability density',
			name='Permutation Null Dist',
			marker_color='lightgray',
			opacity=0.7,
			nbinsx=50,
			marker_line=dict(width=1, color='gray')
		))

		# 2.2 Adds the KDE (permutation test)
		fig.add_trace(go.Scatter(
			x=x_range,
			y=kde_y,
			mode='lines',
			name='KDE (Permutation)',
			line=dict(color='royalblue', width=2.5)
		))

		# 2.3 Adds observed delta
		fig.add_vline(
			x=delta_obs,
			line_width=2,
			line_dash="dash",
			line_color="dimgray",
			annotation_text=rf"<b>Observed $\Delta$ ({delta_obs:.2f})</b>",
			annotation_position="top right",
			annotation_font=dict(size=12, color="dimgray")
		)

		# 3. The central limit theorem curve for comparison
		if include_clt:
			# 3.1 Compute the pooled variance
			var_a = np.var(self._a_samples, ddof=1)
			var_b = np.var(self._b_samples, ddof=1)
			n_a = len(self._a_samples)
			n_b = len(self._b_samples)

			pooled_var = ((n_a - 1) * var_a + (n_b - 1) * var_b) / (n_a + n_b - 2)
			se_diff = np.sqrt(pooled_var * (1 / n_a + 1 / n_b))

			# 3.2 Central limit theorem for null hypothesis: mean zero and variance
			#    defined by the pooled variance
			clt_dist = norm.pdf(x_range, 0, se_diff)

			# 3.3 Adds the gaussian to the plot
			fig.add_trace(go.Scatter(
				x=x_range,
				y=clt_dist,
				mode='lines',
				name='CLT Normal Dist',
				line=dict(color='firebrick', width=2.5, dash='dash')
			))

		# 4. Styling settings
		fig.update_layout(
			title=dict(
				text='<b>A/B Test Null Distribution: Permutation vs. CLT</b>',
				font=dict(size=20),
				y=0.95,
				x=0.5,
				xanchor='center',
				yanchor='top'
			),
			xaxis_title=r'<b>$\Delta$ (Mean B - Mean A)</b>',
			yaxis_title='<b>Density</b>',
			barmode='overlay',
			plot_bgcolor='white',
			hovermode='x unified',
			legend=dict(
				yanchor="top",
				y=0.99,
				xanchor="left",
				x=0.01,
				bgcolor='rgba(255, 255, 255, 0.8)',
				bordercolor='lightgray',
				borderwidth=1
			),
			margin=dict(l=60, r=40, t=80, b=60),
			height=600,
			width=800
		)

		# 5. Computes padding given the amplitude of the graph
		dist_min = min(delta_distribution)
		dist_max = max(max(delta_distribution), delta_obs)
		amplitude = dist_max - dist_min
		padding = amplitude * 0.1 # 10% padding

		# 6. Styling the axes
		fig.update_xaxes(range=[dist_min - padding, dist_max + padding], showline=True, linewidth=1, linecolor='lightgray', gridcolor='whitesmoke')
		fig.update_yaxes(showline=True, linewidth=1, linecolor='lightgray', gridcolor='whitesmoke')

		# Returns the graph
		return fig